#!/bin/sh
set -e

case "$1" in
remove)
	update-alternatives --remove \
		u-boot-rk3588-axon-cm-evb1-idbloader \
		/usr/lib/u-boot/rk3588-axon-cm-evb1/idbloader.img

	update-alternatives --remove \
		u-boot-rk3588-axon-cm-evb1-uboot \
		/usr/lib/u-boot/rk3588-axon-cm-evb1/u-boot.img
	;;

failed-upgrade | deconfigure) ;;

*)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
